config/routes.rb
Benri::Application.routes.draw do
  resources :bugs

  resources :bugs do
    collection do
      get :search
    end
  end

  resources :browsers

  get "post/index"

  get "search/index"

end

app/models/browser.rb
class Browser < ActiveRecord::Base
end

app/models/bug.rb
class Bug < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/browsers_controller.rb
class BrowsersController < ApplicationController
  # GET /browsers
  # GET /browsers.json
  def index
    @browsers = Browser.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @browsers }
    end
  end

  # GET /browsers/1
  # GET /browsers/1.json
  def show
    @browser = Browser.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @browser }
    end
  end

  # GET /browsers/new
  # GET /browsers/new.json
  def new
    @browser = Browser.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @browser }
    end
  end

  # GET /browsers/1/edit
  def edit
    @browser = Browser.find(params[:id])
  end

  # POST /browsers
  # POST /browsers.json
  def create
    @browser = Browser.new(params[:browser])

    respond_to do |format|
      if @browser.save
        format.html { redirect_to @browser, notice: 'Browser was successfully created.' }
        format.json { render json: @browser, status: :created, location: @browser }
      else
        format.html { render action: "new" }
        format.json { render json: @browser.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /browsers/1
  # PUT /browsers/1.json
  def update
    @browser = Browser.find(params[:id])

    respond_to do |format|
      if @browser.update_attributes(params[:browser])
        format.html { redirect_to @browser, notice: 'Browser was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @browser.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /browsers/1
  # DELETE /browsers/1.json
  def destroy
    @browser = Browser.find(params[:id])
    @browser.destroy

    respond_to do |format|
      format.html { redirect_to browsers_url }
      format.json { head :ok }
    end
  end
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  # GET /bugs
  # GET /bugs.json
  def index
    @bugs = Bug.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bugs }
    end
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def search
    @bugs = Bug.all

    respond_to do |format|
      format.html # search.html.erb
      format.json { render json: @bugs }
    end
  end

  # GET /bugs/1
  # GET /bugs/1.json
  def show
    @bug = Bug.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bug }
    end
  end

  # GET /bugs/new
  # GET /bugs/new.json
  def new
    @bug = Bug.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bug }
    end
  end

  # GET /bugs/1/edit
  def edit
    @bug = Bug.find(params[:id])
  end

  # POST /bugs
  # POST /bugs.json
  def create
    @bug = Bug.new(params[:bug])

    respond_to do |format|
      if @bug.save
        format.html { redirect_to @bug, notice: 'Bug was successfully created.' }
        format.json { render json: @bug, status: :created, location: @bug }
      else
        format.html { render action: "new" }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bugs/1
  # PUT /bugs/1.json
  def update
    @bug = Bug.find(params[:id])

    respond_to do |format|
      if @bug.update_attributes(params[:bug])
        format.html { redirect_to @bug, notice: 'Bug was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bug.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bugs/1
  # DELETE /bugs/1.json
  def destroy
    @bug = Bug.find(params[:id])
    @bug.destroy

    respond_to do |format|
      format.html { redirect_to bugs_url }
      format.json { head :ok }
    end
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
  end

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/browsers_helper.rb
module BrowsersHelper
end

app/helpers/bugs_helper.rb
module BugsHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/browsers/_form.html.erb
<%= form_for(@browser) do |f| %>
	<% if @browser.errors.any? %>
		<div id="error_explanation">
		<h2><%= pluralize(@browser.errors.count, "error") %> prohibited this browser from being saved:</h2>

		<ul>
		<% @browser.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
		</div>
	<% end %>

<!--
	<div class="field">
		<%= f.label :id %><br />
		<%= f.number_field :id %>
	</div>
-->
	<div class="form">
		<dl>
			<dt><%= f.label :"ブラウザ" %></dt>
			<dd><%= f.text_field :name %></dd>
		</dl>
		<dl>
			<dt><%= f.label :"バージョン" %></dd>
			<dd><%= f.text_field :version %></dd>
		</dl>
		<p class="actions"><%= f.submit :"登録" %></p>
	</div>
<% end %>

app/views/browsers/edit.html.erb
<p class="lead">ブラウザを修正します</p>

<%= render 'form' %>

app/views/browsers/index.html.erb
<p class="lead">ブラウザ一覧</p>

<table>
<tr>
<th>Name</th>
<th>Version</th>
<th></th>
</tr>

<% @browsers.each do |browser| %>
<tr>
<td><%= browser.name %></td>
<td><%= browser.version %></td>
<td class="showBtn"><%= link_to 'Show', browser %></td>
</tr>
<% end %>
</table>

app/views/browsers/new.html.erb
<p class="lead">ブラウザを追加します</p>

<%= render 'form' %>

app/views/browsers/show.html.erb
<div class="show">

<ul>
<li class="editBtn"><%= link_to '編集する', edit_browser_path(@browsers) %></li>
<li class="removeBtn"><%= link_to '削除する', @browsers, confirm: '本当に削除してよいですか', method: :delete %></li>
</ul>

<dl>
<dt>ブラウザ</dt>
<dd><%= @browser.name %></dd>
</dl>

<dl>
<dt>バージョン</dt>
<dd><%= @browser.version %></dd>
</dl>

</div>

app/views/bugs/_form.html.erb
<%= form_for(@bug) do |f| %>
	<% if @bug.errors.any? %>
		<div id="error_explanation">
			<h2><%= pluralize(@bug.errors.count, "error") %> prohibited this bug from being saved:</h2>

			<ul>
				<% @bug.errors.full_messages.each do |msg| %>
					<li><%= msg %></li>
				<% end %>
			</ul>
		</div>
	<% end %>

	<div class="form">
		<dl>
			<dt><%= f.label :"バグ" %></dd>
			<dd><%= f.text_area :title %></dd>
		</dl>
		<dl>
			<dt><%= f.label :"発生するブラウザ" %></dt>
			<dd><%= select_tag('browser', options_for_select({'IE7'=>1,'IE8'=>2,'Chrome'=>3})) %></dd>
		</dl>
		<dl>
			<dt><%= f.label :"詳細" %></dt>
			<dd><%= f.text_area :detail %></dd>
		</dl>
		<dl>
			<dt><%= f.label :"対処法" %></dt>
			<dd><%= f.text_area :process %></dd>
		</dl>
		<p class="actions"><%= f.submit :"登録" %></p>
	</div>
<% end %>

app/views/bugs/_search.html.erb
<div class="search">
<%= form_tag( {:controller=>"bugs", :action=>"search"}, {:method=>"get"} ) do %>

<p class="searchBox"><%= text_field_tag "keyword", "", {:size=>30} %></p>
<p class="submit"><%= submit_tag "検索" %></p>

<% end %>
</div>

app/views/bugs/edit.html.erb
<p class="lead">バグを修正します</p>

<%= render 'form' %>

app/views/bugs/index.html.erb
<p class="lead">バグを検索します</p>

<%= render 'search' %>

<table>
<tr>
<th width='500'>Title</th>
<th></th>
</tr>

<% @bugs.each do |bug| %>
<tr>
<td><%= bug.title %></td>
<td><p class="showBtn"><%= link_to 'Show', bug %></p></td>
</tr>
<% end %>
</table>

app/views/bugs/new.html.erb
<p class="lead">バグを追加します</p>

<%= render 'form' %>

app/views/bugs/search.html.erb
<p class="lead">バグを検索します</p>

<table>
<tr>
<th width='500'>Title</th>
<th></th>
</tr>

<% @bugs.each do |bug| %>
<tr>
<td><%= bug.title %></td>
<td><p class="showBtn"><%= link_to 'Show', bug %></p></td>
</tr>
<% end %>
</table>

app/views/bugs/show.html.erb
<div class="show">

<ul>
<li class="editBtn"><%= link_to '編集する', edit_bug_path(@bug) %></li>
<li class="removeBtn"><%= link_to '削除する', @bug, confirm: '本当に削除してよいですか', method: :delete %></li>
</ul>

<dl>
<dt>バグ</dt>
<dd><%= @bug.title %></dd>
</dl>

<dl>
<dt>詳細</dt>
<dd><%= @bug.detail %></dd>
</dl>

<dl>
<dt>対処法</dt>
<dd><%= @bug.process %></dd>
</dl>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Benri</title>
<link href='http://fonts.googleapis.com/css?family=Raleway:100' rel='stylesheet' type='text/css'>
<%= stylesheet_link_tag    "application" %>
<%= javascript_include_tag "application" %>
<%= csrf_meta_tags %>
</head>
<body>
<div class="wrap">

<header>
<h1><a href="/">Bug Management Tool</a></h1>
</header>

<%= yield %>

<footer>
<p>© 2011 naver SUI</p>
</footer>

<!-- /.wrap --></div>
</body>
</html>

app/views/post/index.html.erb
<h1>Post#index</h1>
<p>Find me in app/views/post/index.html.erb</p>

app/views/search/index.html.erb
<h1>Search#index</h1>
<p>Find me in app/views/search/index.html.erb</p>